services:
  node0:
    image: apache/activemq-artemis
    volumes:
      - ./node0:/var/lib/artemis/etc-override
    environment:
      ENABLE_JMX_EXPORTER: "true"
      ARTEMIS_MIN_MEMORY: "1512M"
      ARTEMIS_MAX_MEMORY: "2000M"
      ARTEMIS_USERNAME: "artemis"
      ARTEMIS_PASSWORD: "test"
    ports:
      - "8161:8161"
      - "61616:61616"
  node1:
    image: apache/activemq-artemis
    volumes:
      - ./node1:/var/lib/artemis/etc-override
    environment:
      ENABLE_JMX_EXPORTER: "true"
      ARTEMIS_MIN_MEMORY: "1512M"
      ARTEMIS_MAX_MEMORY: "2000M"
      ARTEMIS_USERNAME: "artemis"
      ARTEMIS_PASSWORD: "test"
    ports:
      - "8162:8161"
      - "61617:61616"
  node2:
    image: apache/activemq-artemis
    volumes:
      - ./node2:/var/lib/artemis/etc-override
    environment:
      ENABLE_JMX_EXPORTER: "true"
      ARTEMIS_MIN_MEMORY: "1512M"
      ARTEMIS_MAX_MEMORY: "2000M"
      ARTEMIS_USERNAME: "artemis"
      ARTEMIS_PASSWORD: "test"
    ports:
      - "8163:8161"
      - "61618:61616"
